# Site settings
title: Captured by Levi
description: I'm a college student with an interest in wildlife and landscape photography.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
instagram_url: https://www.instagram.com/levi_al05/
linkedin_url: https://www.linkedin.com/in/levi-layne

# Build settings
markdown: kramdown
